# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27c91d124f5efb1e57fecd577e2c870e54e653f81db9a4ddc5b99461bc7ec8647c0d97ec715e22ae32bd5be4f143651781ea29b409566b497357b18d66139c89

test:
  secret_key_base: 8f14110031cd946272901ddbd02f629a485196a90adfabacbe9eab7b90c61ce3e9466a56090a3f8f8665c81ab986d4eea067972aee15585d155a0f29755be40a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
